export const START_GAME = 'START_GAME';
export const RESET_GAME_STATUS = 'RESET_GAME_STATUS';
export const CREATE_DECKS = 'CREATE_DECKS';
export const REMOVE_SUIT = 'REMOVE_SUIT';
export const ADD_SUIT_TO_PLAYERS_HAND = 'ADD_SUIT_TO_PLAYERS_HAND';
export const ADD_SUIT_TO_DEALERS_HAND = 'ADD_SUIT_TO_DEALERS_HAND';
export const UPDATE_DEALERS_SHOE_SUIT_GROUPS = 'UPDATE_DEALERS_SHOE_SUIT_GROUPS';